server:
  port: 8088

spring:
  datasource:
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.movie: DEBUG
    org.springframework: INFO
